include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - public_member_api_docs

analyzer:
  exclude:
    - lib/builder/**
    - lib/example/**
    - lib/src/shaders/**

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
